### ISSUE TITLE
Official plugin ?

### ISSUE THREAD

**Issue by pierre-H** [Setono/SyliusPromotionExtensionsPlugin#1]
Hello,

Thank you for your work !

Do you plan to make this plugin (and also all others Setono Sylius plugins) [approved by Sylius](https://docs.sylius.com/en/1.5/plugins/approved-plugins.html) ?

**Comment by loevgaard** [comment]
Yes, that's the plan. Sylius core members are pretty busy. That is why a lot of our plugins are not approved yet :)
